engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  nodesecurity:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - bin/*
  - controller/*
  - helper/*
  - model/*
  - *.js
